# Site settings
title: Slime Mom
tag_text: Slime Mom
description: Worker owned and governed cooperative, supplying freelance contracts, benefits, and resume-enhancing opportunities for experiencers of transmisogyny and some of their allies.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
