# Site settings
title: Slime Mom
tag_text: Slime Mom
description: Democratic anarchist communist worker cooperative, working to create revenue and resume-enhancing opportunities for experiencers of transmisogyny and some of their allies.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
